# Generated by Django 5.1.1 on 2024-09-21 17:24

import apps.task_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0008_worker_profile_image_alter_worker_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worker",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=apps.task_manager.models.user_directory_path,
            ),
        ),
    ]
