# Generated by Django 5.1.1 on 2024-09-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0009_alter_worker_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
