# Generated by Django 5.1.1 on 2024-09-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0010_worker_is_online"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("color", models.CharField(default="#FFFFFF", max_length=7)),
            ],
        ),
    ]
