# Generated by Django 5.1.1 on 2024-09-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_manager", "0011_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="task_manager.tag"
            ),
        ),
    ]
