# Generated by Django 5.1.1 on 2024-09-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_focus", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(
                choices=[(1, "Urgent"), (2, "High"), (3, "Medium"), (4, "Low")],
                default=3,
            ),
        ),
    ]
